### ISSUE TITLE
not connected to printer in D4 desktop 

### ISSUE THREAD

**Issue by MohammedKarman80** [iminsoftware/PrinterDemo#1]
when i install the demo app to my D4 desktop device it is not connected to the printer and return -1 and unknown status . even thought when i install demo app from store it works fine and print . 
is there any extra code shall i add ?

**Comment by nguyenhunq221** [comment]
give more detail guild to add sdk to app in document

**Comment by iminsoftware** [comment]
D4台式机不支持
